version: '3.8'

services:
  open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
    ports:
      - "3000:3000"
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      RABBITMQ_USERNAME: group_5IT
      RABBITMQ_PASSWORD: group_5IT
    volumes:
      -  rabbitmq_data:/data
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: group_5IT
      MINIO_ROOT_PASSWORD: group_5IT
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3
volumes:
  minio-storage:
  rabbitmq_data: